# Generated by Django 3.0.2 on 2020-01-24 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('content', models.TextField(max_length=1024)),
                ('author', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='pictures/')),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 19, 27, 58, 210713, tzinfo=utc))),
                ('source', models.URLField()),
            ],
        ),
    ]
